---
global:
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  #  - maxSkew: 1
  #    topologyKey: topology.kubernetes.io/zone
  #    whenUnsatisfiable: ScheduleAnyway
  #    matchLabelKeys:
  #      - pod-template-hash
  #  - maxSkew: 1
  #    topologyKey: kubernetes.io/hostname
  #    whenUnsatisfiable: DoNotSchedule
  #    matchLabelKeys:
  #      - pod-template-hash
  affinity: {}
  # -- Global hostAliases to be applied to all deployments
  hostAliases: []
  # -- Global pod labels to be applied to all deployments
  podLabels: {}
  # -- Global pod annotations to be applied to all deployments
  podAnnotations: {}
  # -- Global imagePullSecrets to be applied to all deployments
  imagePullSecrets: []
  # -- Global image repository to be applied to all deployments
  repository: ""
  compatibility:
    openshift:
      # -- Manages the securityContext properties to make them compatible with OpenShift.
      # Possible values:
      # auto - Apply configurations if it is detected that OpenShift is the target platform.
      # force - Always apply configurations.
      # disabled - No modification applied.
      adaptSecurityContext: auto

replicaCount: 1
